Repository yvonne0711/sales-tracker, pull requests merged in 2025-10, with the labels that each got.

#68 Added a PR template for future PRs
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: feature

#80 [PR] Workflow enhancement
  .github/workflows/main.yaml
Labels: bug

#94 [PR] Changed ECR comment
  terraform/phase_one/main.tf
Labels: enhancement

#96 [PR] Updated Architecture Diagram
  diagrams/architecture_diagram.jpg
  diagrams/architecture_diagram.png
Labels: enhancement

#87 [PR] Dockerfile for generating email script
  email/dockerfile
  email/report.py
Labels: feature

#92 Add drop table if exists
  database/schema.sql
Labels: enhancement

#102 add in eventbridge iam role policy and scheduler
  terraform/phase_two/main.tf
Labels: feature

#120 [PR] Added policy 'send email' for lambda
  terraform/phase_two/main.tf
Labels: feature

#124 Added tests for subscriptions
  scraper/requirements.txt
  scraper/subscriptions/dockerfile
  scraper/subscriptions/insert_product.sh
  scraper/subscriptions/requirements.txt
  scraper/subscriptions/subscription.py
  scraper/subscriptions/test_subscriptions.py
Labels: feature

#133 [PR] Uploaded eventbridge to AWS
  terraform/phase_two/main.tf
Labels: feature

#143 [PR] ECS dashboard on AWS
  terraform/phase_two/main.tf
Labels: feature

#140 Added passwords for users
  dashboard/password/passwords.py
  dashboard/password/requirements.txt
  dashboard/password/test_passwords.py
Labels: feature

#182 [PR] JD ECR and lambda setup
  terraform/main.tf
  terraform/phase_one/main.tf
  terraform/phase_two/main.tf
  terraform/phase_two/variables.tf
  terraform/variables.tf
Labels: feature

#190 [PR] Dashboard Price History Page
  dashboard/login.py
  dashboard/login_functions.py
  dashboard/pages/price_history_page.py
Labels: feature

#197 added password check
  dashboard/login.py
  dashboard/test_login.py
Labels: enhancement

#196 [PR] Fixed price history page bugs
  dashboard/pages/price_history_page.py
Labels: bug, enhancement

#199 streamlit colour theme
  dashboard/.streamlit/config.toml
Labels: enhancement

#217 [PR] Dashboard home page
  dashboard/login_functions.py
  dashboard/pages/home_page.py
  dashboard/pages/price_history_page.py
Labels: feature

#240 Feature scrape product name
  dashboard/pages/track_new_product.py
  dashboard/scraper_functions.py
Labels: enhancement

#244 added readme for subscription
  subscriptions/README.md
Labels: documentation

#243 [PR] Fixed desired price bug and added custom colours for pie chart
  dashboard/pages/home_page.py
  dashboard/pages/price_history_page.py
Labels: bug, enhancement
